#ifndef FGEDEFINITION_H
#define FGEDEFINITION_H


#define FGE_SELECTION    1
#define FGE_NO_SELECTION 0

#define FGE_SELECTION_OBJECT       0
#define FGE_SELECTION_POINT        1
#define FGE_SELECTION_EDGE         2
#define FGE_SELECTION_FACE         3

#define FGE_DISPLAY_MODE_WIRE           0
#define FGE_DISPLAY_MODE_SOLID          1
#define FGE_DISPLAY_MODE_WIRE_SOLID     2
#define FGE_DISPLAY_MODE_MATERIAL       3
#define FGE_DISPLAY_MODE_WIRE_MATERIAL  4
#define FGE_DISPLAY_MODE_OUTLINE        5


#define FGE_OBJECT_MESH       0
#define FGE_OBJECT_CURVE      1
#define FGE_OBJECT_SURFACE    2
#define FGE_OBJECT_TEXT       3
#define FGE_OBJECT_ARMATURE   4

//interaction between mode into object mesh
#define FGE_INTERACTION_MODE_OBJECT         0
#define FGE_INTERACTION_MODE_EDIT           1
#define FGE_INTERACTION_MODE_POSE           2
#define FGE_INTERACTION_MODE_SCULPT         3
#define FGE_INTERACTION_MODE_VERTEX_PAINT   4
#define FGE_INTERACTION_MODE_WEIGHT_PAINT   5
#define FGE_INTERACTION_MODE_TEXTURE_PAINT  6


#define FGE_MESH_SELECT_VERTEX   1
#define FGE_MESH_SELECT_EDGE     2
#define FGE_MESH_SELECT_FACE     3

#define FGE_VIEWPORT_SHADING_WIREFRAME		0
#define FGE_VIEWPORT_SHADING_WIRESOLID		1
#define FGE_VIEWPORT_SHADING_SOLID			2
#define FGE_VIEWPORT_SHADING_MATERIAL		3
#define FGE_VIEWPORT_SHADING_WIREMATERIAL	4
#define FGE_VIEWPORT_SHADING_OUTLINE		5


#define FGE_SELECT_ITEMS_DISABLED	0
#define FGE_SELECT_ITEMS_TWEAK		1
#define FGE_SELECT_ITEMS_RECT		2
#define FGE_SELECT_ITEMS_CIRCLE		3
#define FGE_SELECT_ITEMS_LASSO		4

#define FGE_TRANSFORM_SELECTED_ITEMS_MOVE			1
#define FGE_TRANSFORM_SELECTED_ITEMS_ROTATE			2
#define FGE_TRANSFORM_SELECTED_ITEMS_SCALE			3
#define FGE_TRANSFORM_SELECTED_ITEMS_COMBINATION	4


#endif // FGEDEFINITION_H
